### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by brean** [Chaduke/paddles_balls_blocks_walls#1]
Please add a license file with information for the assets and code.

**Comment by Chaduke** [comment]
Will do.  I've been using Creative Commons Zero, basically anyone can do whatever they want with it.   I'm not super familiar with licensing so if you have any suggestions here feel free, or really on anything in the project.    Will add a file on my next commit today.  Thanks!

**Comment by Chaduke** [comment]
Also, the original game was released as freeware and I think the author might work for (or has worked for) Nintendo now, so I'm going to try my best to get in contact with him and see if I can get any kind of response.
