### ISSUE TITLE
The game is not ending when the last block is destroyed

### ISSUE THREAD

**Issue by kodbilenadam** [Chaduke/paddles_balls_blocks_walls#5]
Hey I have been playing the game for couple of hours. If I remember correctly from the original the game supposed to end when the last block is destroyed. But in this case it waits for the destroy animation of the block to finish to end the game. Before this if you lose your last ball it becomes a game over screen.

**Comment by Chaduke** [comment]
Did some major updates to collisions and how blocks are destroyed today.  Should have an update out by this evening.  I'll drop a line here for you when that happens.

**Comment by kodbilenadam** [comment]
I'll be waiting! I don't have that much experience with Godot but I'll try to help if i can find some time! :)

**Comment by Chaduke** [comment]
Ok the update is up!  Let me know what you think.

**Comment by Chaduke** [comment]
Closing issue as game has progressed significantly since this was posted.
